### ISSUE TITLE
Current Status

### ISSUE THREAD

**Issue by fridlmue** [sailfishos-chum/pcsc-ccid#1]
Does build in OBS test-environment successfully with current spec file but **not** with `tar_git`, only with manual upload of the .tar file.
Compare: https://build.sailfishos.org/package/show/home:fridlmue/pcsc-ccid

Depends on:
- https://github.com/sailfishos-chum/pcsc-lite

**Comment by nephros** [comment]
Hi,

I have made some changes which lead to successful build on OBS with tar_git.
Note I have not tested the package, just made it build.

Also, this drops the `Enhances: %USBDRIVERS` magic, if that is required I can maybe restore it - I'm not quite sure how that worked (piping output of `tar x` to `sed` is a first for me) but I'm sure we can grep in the git tree for the same results.  
But I don't think 'Enhances' is used at all on SailfishOS so...

Please see 

 - Step-by-step changes required for OBS building: https://github.com/nephros/pcsc-ccid/tree/to_tar_git

 - The same, with final clean up of .spec file: https://github.com/nephros/pcsc-ccid/tree/to_tar_git_clean

 - The same, squashed, with tagged version bumps: https://github.com/nephros/pcsc-ccid/tree/main


OBS builder:
https://build.sailfishos.org/package/show/home:nephros:branches:home:fridlmue

The git repo commit history is a bit verbose and dirty so I didn't make a PR.
But you can pull and squash at leisure if you find this useful.

**Comment by fridlmue** [comment]
Thanks, @nephros, for investigating and the huge help!

My key takeaways for "tar_git": 
- Shorter Path for `Source`, when URL is specified.
- could be a good idea to check if `autoconf` is needed. (How did you know? From experience?)

Perhaps its a good Idea, to "reset" the local commit history to a finally working state then. ;-) 

I'll first merge the 1.4.35, test and try to fix some other packages with this new insights. Then probably I'll try to bump versions and test again.

**Comment by nephros** [comment]
> * could be a good idea to check if `autoconf` is needed. (How did you know? From experience?)

Well, git sources typically do not come with a read-to-run `configure` script, it must be generated from the autotools bits shipped with the source. And this is the case here.  
That I learned from experience indeed when moving other things to `tar_git` packaging.

In the case of this package, `autoconf-archive` is definitely needed in addition because it contains m4 macros necessary for autotools bootstrapping.

Now, I believe the OBS build environment already contains autoconf (not sure), but I find that it's always good to have the build requirements generic, and not tailored to the build environment.

(See also: moving from SFOS SDK requires you to e.g. put all the Qt modules in the .spec even though it builds fine in the SDK without them. OBS does not have them installed per default.)

**Comment by nephros** [comment]
> * Shorter Path for `Source`, when URL is specified.

I believe the OBS builder does not use the URL given in `Source`, apart from taking the packaging name and compression format from it. So it's sufficient to use `%{name}-%{version}.tar.gz` for any package. More important is the `%setup` part which, if using a submodule called foo, must always be `%setup -n %{name}-{%version}/foo` because that is how the tarball on OBS is structured.  
That is why I always call my submodules `upstream`, so most specs have the same `%setup` line.

**Comment by fridlmue** [comment]
It is working, thanks for the help again!
